development:
  bucket: dmitexas-dev
  access_key_id: AKIAI2HUYURFJ4CI4ZGA
  secret_access_key: 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
  max_file_size: 10485760
  acl: public-read
    
test:
  bucket: dmitexas-dev
  access_key_id: AKIAI2HUYURFJ4CI4ZGA
  secret_access_key: 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
  max_file_size: 10485760
  acl: public-read
  
production:
  bucket: dmitexas
  access_key_id: AKIAI2HUYURFJ4CI4ZGA
  secret_access_key: 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
  max_file_size: 10485760
  acl: public-read
