# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

common: &common
  adapter: postgresql
  username: user
  password: password

development:
  <<: *common
  database: dmtraining_development

test:
  <<: *common
  database: dmtraining_test

production:
  <<: *common
  database: dmtraining_production
